eureka:
  client:
    serviceUrl:
      defaultZone: http://userID:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30